TravelAgency/Controllers/GuestRegistrationController.cs
using System.Linq;
using System.Web.Mvc;
using TravelAgency.DAL;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    public class GuestRegistrationController : Controller
    {
        private readonly ITravelAgencyRepository _repository;
        public GuestRegistrationController(ITravelAgencyRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Create(int legId)
        {
            ViewBag.GuestList = _repository.GetGuests().Select(g=>new{id=g.Id, value=g.FirstName}).Distinct();
            ViewBag.LegId = legId;
            
            
            return PartialView();
        }


        [HttpPost]
        public ActionResult Create(GuestRegistration registration)
        {
            if (ModelState.IsValid)
            {
                _repository.AddGuestRegistration(registration);
                var leg=_repository.GetLeg(registration.LegId);
                UpdateViable(leg.TripId);                 
                return RedirectToAction("Index", "Home");
            }
            ViewBag.GuestList = _repository.GetGuests().Select(g => new { id = g.Id, value = g.FirstName }).Distinct();
            ViewBag.LegId = registration.LegId;
            return PartialView();
        }

        public JsonResult IsAlreadyRegistered(int guestId , int legId)
        {
            return Json(_repository.GetGuestRegistrationsByLegAndGuest(legId, guestId).Any(),
                JsonRequestBehavior.AllowGet);
        }


        public void UpdateViable(int tripId)
        {
            var trip = _repository.GetTrip(tripId);
            if (IsViable(trip))
            {
                trip.Viable = true;
                _repository.UpdateTrip(trip);
            }
        }

        public bool IsViable(Trip trip)
        {
            return (_repository.GetNoGuestsOnTrip(trip.Id) >= trip.MinimumGuests);
        }
    }
    }

TravelAgency/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TravelAgency.DAL;
using TravelAgency.HelperClasses;
using TravelAgency.Models;


namespace TravelAgency.Controllers
{
    public class HomeController : Controller
    {


        private readonly ITravelAgencyRepository _repository;

        public HomeController(ITravelAgencyRepository repository)
        {
            _repository = repository;
        }


        public ActionResult Index()
        {
            var trips = _repository.GetAllTrips();
            return View(trips.ToList());
        }

        public ActionResult TripDetails(int tripId)
        {
            var legs = _repository.GetLegsForTrip(tripId);
            return PartialView("_LegList", legs);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Trip trip)
        {
            if (ModelState.IsValid)
            {
                trip.Viable = false;
                trip.Complete = false;
                trip.PicturePath = "~/Images/default.jpg";

                _repository.AddTrip(trip);

                return RedirectToAction("Index");
            }
            return View();
        }


        public ActionResult GetGuestsOnLeg(int legId)
        {
            var guests = _repository.GetGuestsOnLeg(legId);
            if (!guests.Any())
                ViewBag.NoGuests = "empty";
            var leg = _repository.GetLeg(legId);
            ViewBag.Start = leg.StartLocation;
            ViewBag.Finish = leg.FinishLocation;
            ViewBag.LegId = leg.Id;
            return PartialView("_GuestList", guests);
        }

        public ActionResult GetProgressBar(int tripId)
        {

            var trip = _repository.GetTrip(tripId);
            var legs = _repository.GetLegsForTrip(tripId);

            var tripPeriod = trip.FinishDate.Subtract(trip.StartDate).TotalDays;
            var list = new List<TripTimelineElement>();

            var auxFinish = trip.StartDate;
            var progress = 0;
            foreach (var leg in legs)
            {

                if (auxFinish != leg.StartDate)
                {
                    var period = leg.StartDate.Subtract(auxFinish).TotalDays;
                    var yyy = new TripTimelineElement
                    {
                        StartDate = auxFinish.ToString("dd/MM"),
                        FinishDate = leg.StartDate.ToString("dd/MM"),
                        Percentage = (int)(period / tripPeriod * 100),
                        CssClass = "progress-bar progress-bar-danger",
                        NotPlanned = true
                    };
                    progress += yyy.Percentage;

                    list.Add(yyy);
                }

                {
                    var legPeriod = leg.FinishDate.Subtract(leg.StartDate).TotalDays;
                    var yyy = new TripTimelineElement
                    {
                        Percentage = (int)(legPeriod / tripPeriod * 100),
                        StartDate = leg.StartDate.ToString("dd/MM"),
                        FinishDate = leg.FinishDate.ToString("dd/MM"),
                        CssClass = "progress-bar progress-bar-success",
                        NotPlanned = false

                    };
                    list.Add(yyy);
                    progress += yyy.Percentage;
                }

                auxFinish = leg.FinishDate;
            }
            if (auxFinish != trip.FinishDate)
            {

                var yyy = new TripTimelineElement
                 {
                     Percentage = (int)(trip.FinishDate.Subtract(auxFinish).TotalDays / tripPeriod * 100),
                     StartDate = auxFinish.ToString("dd/MM"),
                     FinishDate = trip.FinishDate.ToString("dd/MM"),
                     CssClass = "progress-bar progress-bar-danger",
                     NotPlanned = true
                 };
                list.Add(yyy);
                progress += yyy.Percentage;
            }

            if (progress != 100)
            {
                list.Last().Percentage += (100 - progress);
            }

            return PartialView("_TimeLine", list);
        }
    }
}

TravelAgency/Controllers/LegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using TravelAgency.DAL;
using System.Web.Mvc;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    public class LegController : Controller
    {
        private readonly ITravelAgencyRepository _repository;

        public LegController(ITravelAgencyRepository repository)
        {
            _repository = repository;
        }


        public ActionResult Create()
        {
         
            ViewBag.TripList = _repository.GetAllTrips().Select(t => new { id = t.Id, value = t.Name }).Distinct();
            
            return View();
        }

        [HttpPost]
        public ActionResult Create(Leg newLeg)
        {
            if (ModelState.IsValid)
            {
                if (!IsClashing(newLeg))
                {
                    _repository.AddLeg(newLeg);
                    UpdateComplete(newLeg.TripId);
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.ErrorMessage = "Dates are clashing on other legs. Check timeline";
            }

            ViewBag.TripList = _repository.GetAllTrips().Select(t => new { id = t.Id, value = t.Name }).Distinct();
        
            return View();

        }

        public bool IsDateInLegs(DateTime date, IEnumerable<Leg> legs)
        {
             foreach (var leg in legs)
                {
                    if (DateTime.Compare(date, leg.StartDate)>=0 
                        && DateTime.Compare(date,leg.FinishDate)<=0)
                    {
                        return true;

                    }
                    if (DateTime.Compare(date,leg.StartDate)<0)

                    {
                        return false;
                    }

                }
            return false;
        }

        public bool IsComplete(Trip trip)
        {
            var tripStartDate = trip.StartDate;
            var tripEndDate = trip.FinishDate;
            var legs = _repository.GetLegsForTrip(trip.Id);

            while (tripStartDate <= tripEndDate)
            {
               if(!IsDateInLegs(tripStartDate, legs))
                   return false;
               tripStartDate=tripStartDate.AddDays(1);
            }
            return true;

        }

        public void UpdateComplete(int tripId)
        {
            var trip = _repository.GetTrip(tripId);
            if (IsComplete(trip))
            {
                trip.Complete = true;
                _repository.UpdateTrip(trip);
            }
        }

    
        [HttpPost]
        public JsonResult StartDateOutsideTrip(DateTime startdate, int tripId)
        {
            var trip = _repository.GetTrip(tripId);

            if (DateTime.Compare(startdate, trip.StartDate) < 0)
                return Json(false, JsonRequestBehavior.AllowGet);

            if (DateTime.Compare(startdate, trip.FinishDate) > 0)
                return Json(false, JsonRequestBehavior.AllowGet);

            return Json(true,JsonRequestBehavior.AllowGet);

            //return
            //    Json(!(DateTime.Compare(startdate, trip.StartDate) < 0 
            //            || DateTime.Compare(startdate, trip.FinishDate) > 0),JsonRequestBehavior.AllowGet);


        }

        public JsonResult FinishDateOutsideTrip(DateTime finishdate, int tripId)
        {
            var trip = _repository.GetTrip(tripId);

            return Json(!(DateTime.Compare(finishdate, trip.StartDate) < 0 
                       || DateTime.Compare(finishdate, trip.FinishDate) > 0),JsonRequestBehavior.AllowGet);

        
        }

        public bool IsClashing(Leg newLeg)
        {
            var trip = _repository.GetTrip(newLeg.TripId);
            var legs = trip.Legs;
            if (trip.Complete)
                return true;
            foreach (var leg in legs)
            {
                if (newLeg.StartDate >= leg.StartDate && newLeg.StartDate < leg.FinishDate)
                    return true;
                if (newLeg.FinishDate > leg.StartDate && newLeg.FinishDate <= leg.FinishDate)
                    return true;
                if (newLeg.StartDate < leg.StartDate && newLeg.FinishDate > leg.FinishDate)
                    return true;
               
            } 
            return false;
        }
  
    }

}

TravelAgency/Views/Home/Create.cshtml
@model TravelAgency.Models.Trip
<head>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
</head>
@{
    ViewBag.Title = "Add Trip";
}

@section scripts
{
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
   
    <script>
        $(function () {
            $('#datepicker').datepicker({ dateFormat: 'dd/mm/yy'});
            $('#datepicker1').datepicker({ dateFormat: 'dd/mm/yy'});          
        });
    </script>
     @Scripts.Render("~/bundles/jqueryval")
}
<br/>
<br/>
<div>
    @Html.ActionLink("Back to List", "Index",null, new{@class="btn btn-info btn-sm"})
</div>
<br/>
<div class="row">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="col-md-offset-3 well col-md-6">
            <fieldset>
                <legend>New Trip</legend>
              
                <div class="form-group">
                  
                    
                    @Html.LabelFor(model => model.Name)
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Name of the trip" })
                    @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate)
                    @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control ", id = "datepicker" })
                    @Html.ValidationMessageFor(model => model.StartDate,null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FinishDate)
                    @Html.TextBoxFor(model => model.FinishDate, new { @class = "form-control ", id = "datepicker1" })
                    @Html.ValidationMessageFor(model => model.FinishDate,null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MinimumGuests)
                    @Html.TextBoxFor(model => model.MinimumGuests, new { @class = "form-control", placeholder = "Mimimum Number of Guest for trip to be considered Viable" })
                    @Html.ValidationMessageFor(model => model.MinimumGuests,null, new { @class = "text-danger" })
                </div>
                <br/>
                <br/>
                <input type="submit" class="btn btn-success col-md-12" value="Create"/>
            </fieldset>
           
        </div>
        
        <div class="col-md-6"></div>

    }
</div>

TravelAgency/Views/Home/Index.cshtml
@model IEnumerable<TravelAgency.Models.Trip>

@{
    ViewBag.Title = "Index";
}

@section scripts
{
    <script type="text/javascript">

        $(function () {
            $("[data-toggle='tooltip']").tooltip();
        });
        
        function getTimeLine(id) {
            $.ajax({
                url: '@Url.Action("GetProgressBar")',
                data: { tripId: id },
                success: function (data) {
                    $('#timeline_' + id).html(data);
                    $("[data-toggle='tooltip']").tooltip();
                }
            });
        }

        function getTripDetails(tripId) {
            getTimeLine(tripId);
            $.ajax({
                url: "api/LegApi/" + tripId,
                type: "Get",
                success: function (data) {
                    $('#m_' + tripId).empty();

                    $("<div id='guestsModal' class='modal fade' role='dialog' aria-hidden='true'><br /><br />" +
                        "<br /> <div class='col-md-offset-4 col-md-4' id='guestsDetails'></div></div>").appendTo('#m_' + tripId);

                    for (var i = 0; i < data.length; i++) {
                        $("<div class='row' id='" + data[i].Id + "'>" +
                             "<div class='col-md-2 text-right' >" +
                                   "<div class='btn btn-info btn-xs'>" + (i + 1) + "</div>" +
                            "</div>" +
                            "<div class='col-md-9'>" +
                            "<strong>" + data[i].StartLocation + " - " + data[i].FinishLocation + " </strong>" +
                             new Date(data[i].StartDate).toLocaleDateString()+ "-" +
                             new Date(data[i].FinishDate).toLocaleDateString() +
                            "</div>" +
                            "<div class='col-md-1'>" +
                                "<span class='badge' onclick='showGuests(" + data[i].Id + ")' style='cursor: pointer'>" +
                                    data[i].x + " Guests" +
                                 "</span>" +
                            "</div>" +
                        "</div>" +
                        "<br/>"
                            ).appendTo('#m_' + tripId);

                    }
                }
            });

        }
        
        function showGuests(id) {
            $.ajax({
                url: '@Url.Action("GetGuestsOnLeg")',
                data: { legId: id },
                success: function (data) {
                    $('#guestsModal').modal("show");
                    $("#guestsDetails").html(data).modal("show");
                }
            });
        }

    </script>
}

<h2>Trips</h2>

<p>
    @Html.ActionLink("Add New Trip", "Create")
</p>


<div id="guestsModal" class="modal fade" role="dialog" aria-hidden="true">
    <br />
    <br />
    <br />
    <div class="col-md-offset-4 col-md-4" id="guestsDetails">
    </div>
</div>


@foreach (var item in Model)
{
    <div class="row" id="@item.Id" onclick=" getTripDetails(@item.Id)">
        <div class="col-md-4">
            <br />

            <img src="@Url.Content(item.PicturePath)" alt="Album Picture" />
        </div>
        <div class="col-md-3">
            <div class="row text-center">
                <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
            </div>
            <div class="row text-center">
                <h4>@Html.DisplayFor(modelItem => item.StartDate) -
                    @Html.DisplayFor(modelItem => item.FinishDate)</h4>
            </div>
            <div class="row text-center">
                <span class="badge">Min @item.MinimumGuests Guests</span>
            </div>
            <br />
            <div class="row">
                <div class="col-md-offset-2 col-md-4 text-center">
                    <div class=" row">
                        @Html.DisplayNameFor(model => model.Viable)
                    </div>
                    <div class="row">
                        @if (@item.Viable)
                        {
                            <button
                                class="btn-default btn-sm btn-success"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title=""
                                data-original-title="Minimum number of Guest is reached">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button> 
                                               
                        }

                        @if (@item.Viable == false)
                        {
                            <button
                                class="btn-default btn-sm btn-danger"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title=""
                                data-original-title="The minimum number of guests is not reached yet">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button> 
                        }

                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="row">
                        @Html.DisplayNameFor(model => model.Complete)
                    </div>
                    <div class="row">
                        @if (@item.Complete)
                        {
                            <button
                                class="btn-default btn-sm btn-success"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title=""
                                data-original-title="Legs are planned for each day of the trip">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button> 
                        }
                        @if (@item.Complete == false)
                        {
                            <button
                                class="btn-default btn-sm btn-danger"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title=""
                                data-original-title="Legs still missing">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        }
                    </div>
                </div>

            </div>

        </div>
        <div class="col-md-5" id="m_@item.Id"></div>
    </div>
    <div class="row">
        <div class="col-md-7" id="timeline_@item.Id">
        </div>
    </div>
    <br />
    <br />
}

TravelAgency/Views/Home/_GuestList.cshtml
@model IEnumerable<TravelAgency.Models.Guest>
<script>
    $(function() {
        $("[data-toggle='tooltip']").tooltip();
    });

    function addGuest(id) {
        $.ajax({
            url: '@Url.Action("Create","GuestRegistration")',
            data: {legId : id},
            success: function (data) {
                $('#registerForm').html(data);
            }
        });
    }
 
</script>

<div class="modal-content">
    <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Guests on leg
            <br />
            from <b>@ViewBag.Start</b> to <b>@ViewBag.Finish</b> </h4>
    </div>
    <div class="modal-body">
        @if (@ViewBag.NoGuests == "empty")
        {
            <div class="text-center">
                <em>There are no guests in this leg yet!</em>
                <br/>
            </div>
            
        }
        
        @if (@ViewBag.NoGuests != "empty")
        {
            <div class="col-md-offset-1">
                <h4>
                    <b>
                        <em>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </em>
                    </b>
                </h4>

                @foreach (var item in Model)
                {

                    @Html.DisplayFor(modelItem => item.FirstName)
                    <br />
                }

            </div>
        }
        <br/>
        <div class="col-md-offset-5" onclick='addGuest(@ViewBag.LegId)'>
            <button class="btn btn-success btn-lg"
                data-toggle="tooltip"
                data-placement="right"
                title=""
                data-original-title="Add Guest to this leg">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>

    </div>
    <div class="col-md-offset-1" id="registerForm"></div>

</div>

TravelAgency/Views/Home/_LegList.cshtml
@model IEnumerable<TravelAgency.Models.Leg>


<script>

    function black(id) {
        alert(id);
    }
 
  
    function showGuests(id) {
        $.ajax({
            url: '@Url.Action("GetGuestsOnLeg")',
                data: { legId: id },
                success: function (data) {
                    $('#guestsModal').modal("show");
                    $("#guestsDetails").html(data).modal("show");
                }
            });
        }
    //function getLegPicture(cityName, legId) {
    //    $.ajax({
    //        url: 'http://en.wikipedia.org/w/api.php?action=query&prop=images&format=json&imlimit=1&titles=' + cityName,
    //        type: "Get",
    //        success: function (data) {

    //            var img = $("<img />").attr('src', data.result[0].images);
    //            $(img).after('#' + legId);
    //        }

    //    });
    //}
    
   

</script>

<div id="guestsModal" class="modal fade" role="dialog" aria-hidden="true">
    <br />
    <br />
    <br />
    <div class="col-md-offset-4 col-md-4" id="guestsDetails">
    </div>
</div>

@{
    int i = 0;
    foreach (var item in Model)
    {
        i++;
        <div class="row" id="@item.Id">
            <div class="col-md-2 text-right" >
                <div class="btn btn-info btn-xs">@i.</div>

            </div>
           @* <div class="col-md-9" onclick=" getLegPicture('@item.FinishLocation',@item.Id) " style="cursor: pointer">*@
    <div class="col-md-9" onclick="location.href='@Url.Action("GetLegPicture","Leg",new{cityName=item.FinishLocation})'" style="cursor: pointer">
                <strong>
                    @Html.DisplayFor(modelItem => item.StartLocation) -
                    @Html.DisplayFor(modelItem => item.FinishLocation):

                </strong>

                @Html.DisplayFor(modelItem => item.StartDate.Day)-
                @Html.DisplayFor(modelItem => item.FinishDate)

            </div>
            <div class="col-md-1">
                <span class="badge" onclick=" showGuests(@item.Id) " style="cursor: pointer">
                    @Html.DisplayFor(modelItem => item.LegRegistrations.Count) Guests
                </span>
            </div>
        </div>
        <br />
    }
}

TravelAgency/Views/Home/_TimeLine.cshtml
@model IEnumerable<TravelAgency.HelperClasses.TripTimelineElement>

<div class="progress">
    
@{
    int i = 0;
    foreach (var item in Model)
    {
        
        if (@item.NotPlanned)
        {
            <div data-toggle="tooltip"
                 data-placement="bottom"
                 title=""
                 data-original-title="A leg is not planned for this period" 
                 class="@Html.DisplayFor(modelItem => item.CssClass)" style="width: @item.Percentage%;">
                @Html.DisplayFor(modelItem => item.StartDate) - @Html.DisplayFor(modelItem => item.FinishDate) 
                 
                <span class="sr-only"></span>
            </div>
        }
        if (@item.NotPlanned == false)

        {  i++;
            <div 
                data-toggle="tooltip"
                data-placement="bottom"
                title=""
                data-original-title="Leg is Planned"
                class="@Html.DisplayFor(modelItem => item.CssClass)" style="width: @item.Percentage%">
                Leg @i
                <span class="sr-only"></span> 
            </div>
        }
    }
}
    </div >